### ISSUE TITLE
feature: rendering for bolded text 

### ISSUE THREAD

**Issue by Parkertg** [MeanderingProgrammer/markdown.nvim#100]
### Is your feature request related to a problem? Please describe.

right now there is no visual distinction between normal text and bolded text -- thus, all bold text just looks normal instead. aside from the lacking visuals, this also makes editing less convenient as you can't identify bolded sections of text unless you move the cursor to each line  
Normal Mode
![image](https://github.com/user-attachments/assets/eab183c5-aa67-42a2-b15c-c7416c9cea3f)
Insert Mode on boldtext line
![image](https://github.com/user-attachments/assets/e8d1b803-39dc-4986-9659-b831b42a2659)

### Describe the solution you'd like

a. Bold text is bolded (if possible - I presume its not based on it not already being implemented)
b. Bold text has an alternate color - configurable, hopefully with a functional default value
c. Bold text switch to all caps - perhaps this is a separate option to the color option

### Describe alternatives you've considered

- Missing out on that sweet boldness
- Make the bold text the same color as the Link Text color (but probably add an underline to the Link Text to help differentiate it) 

### Additional information

OS: windows
NVIM : 0.9.5
*and I'm currently an nvim noob*

**Comment by MeanderingProgrammer** [comment]
https://github.com/MeanderingProgrammer/markdown.nvim/issues/69

**Comment by MeanderingProgrammer** [comment]
Issue above is about color but same thing, is up to your colorscheme to provide bold & italics parameters to the relevant highlight groups and your terminal emulator to render them correctly.
