### ISSUE TITLE
feature: option to not have heading indent

### ISSUE THREAD

**Issue by chrisgrieser** [MeanderingProgrammer/markdown.nvim#107]
### Is your feature request related to a problem? Please describe.

It's mostly an aesthetic preference – I prefer headings to not have any indentation. The different colors and the numbering are already sufficiently distinguishable for me.

### Describe the solution you'd like

an option to disable heading indent

### Describe alternatives you've considered

I thnk there are none?

**Comment by MeanderingProgrammer** [comment]
Makes sense, added the feature here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/345596bb6ef2b0c0a145c59906c2e84dbddfbbd4

Please update and add the following to your config:

```lua
opts = {
    heading = { position = 'inline' },
}
```

**Comment by chrisgrieser** [comment]
Thank you for the quick implementation! 
Works as expected.
