### ISSUE TITLE
feature: Option for removing top and bottom lines of code blocks

### ISSUE THREAD

**Issue by serhez** [MeanderingProgrammer/markdown.nvim#108]
### Is your feature request related to a problem? Please describe.

Concealed backticks (e.g., ```) leave two additional empty lines on the top and bottom of code blocks. This does not look so good in LSP hover floating windows particularly. Given the new buftype override feature, it would be great to remove these lines completely, like the plugin noice.nvim does for example.

### Describe the solution you'd like

Having an additional option in `code.style` to remove the backtick lines, beside the already existing `none`, `normal`, `language` and `full`.

### Describe alternatives you've considered

N/A.

**Comment by MeanderingProgrammer** [comment]
`noice` is essentially generating a message from scratch: https://github.com/folke/noice.nvim/blob/main/lua/noice/text/markdown.lua#L167, so can easily add / remove text as needed, at least that's how I'm reading what it's doing.

This plugin is working with the underlying buffer and can't overwrite chunks of it. As far as I am aware the only way to remove lines is to do a fold, but a fold for a single line doesn't really work.

I'm open to PRs but don't think there's really a way to accomplish this.

**Comment by serhez** [comment]
That makes sense, thanks for the reply!
