### ISSUE TITLE
feature: Support custom titles for callouts

### ISSUE THREAD

**Issue by AquilesGomez** [MeanderingProgrammer/markdown.nvim#109]
### Neovim version (nvim -v)

0.10.1

### Operating system

MacOS

### Terminal emulator / GUI

Iterm2

### Describe the bug

When I add a title to a callout block header, the rendering
doesn't keep the space between the text properly.
<img width="515" alt="Screenshot 2024-07-31 at 8 25 04 AM" src="https://github.com/user-attachments/assets/6c855012-69b2-430c-9628-c58fc11effc1">

### Expected behavior

I expect the Title to have spaces between the callout block and the title

### Healthcheck output

==============================================================================
render-markdown: require("render-markdown.health").check()

markdown.nvim [neovim version] ~
- OK Version >= 0.10

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown_inline: parser installed
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }
- OK highlights enabled

markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

### Plugin configuration

require("render-markdown").setup {
  callout = {
    done = { raw = "[!Done]", rendered = "󰄬 Done", highlight = "RenderMarkdownSuccess" },
    info = { raw = "[!info]", rendered = "󰋽 Info", highlight = "RenderMarkdownInfo" },
    time = { raw = "[!timestamp]", rendered = " Timestamp", highlight = "RenderMarkdownInfo" },
  },
}

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
While this plugin supports callouts it does not support callouts with custom titles, this is a feature request not a bug. 

Github's parser fails to preview them as well, if you try out:

```
> [!NOTE] TEST
> TEST
```

Here's the result:

> [!NOTE] TEST
> TEST

Normal callouts work though:

```
> [!NOTE]
> TEST
```

> [!NOTE]
> TEST

**Comment by MeanderingProgrammer** [comment]
Ive added support for custom callout titles as documented by obsidian in this commit: https://github.com/MeanderingProgrammer/markdown.nvim/commit/a1bcbf4858d1834f922029b5fc6ae55a7417bd51

Please update and LMK if it works!
