### ISSUE TITLE
bug: diff code blocks not rendering properly in normal mode

### ISSUE THREAD

**Issue by jjohnston-aims** [MeanderingProgrammer/markdown.nvim#110]
### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system

Ubuntu 22.04

### Terminal emulator / GUI

Default Terminal

### Describe the bug

Diff code blocks are not being rendered properly in normal mode.
![image](https://github.com/user-attachments/assets/d902bef7-65e1-41aa-95df-dbff91c0f50d)

But they are in insert mode:
![image](https://github.com/user-attachments/assets/501a7d39-4fdf-41dc-9950-b5f50c7d6871)

### Expected behavior

I would expect to see in normal mode something like what I am seeing in edit mode for diff code blocks.

### Healthcheck output

render-markdown: require("render-markdown.health").check()

markdown.nvim [neovim version] ~
- OK Version >= 0.10

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

### Plugin configuration

Default configuration for [LazyVim](http://www.lazyvim.org/extras/lang/markdown)

```
{
  "MeanderingProgrammer/markdown.nvim",
  opts = {
    file_types = { "markdown", "norg", "rmd", "org" },
    code = {
      sign = false,
      width = "block",
      right_pad = 1,
    },
    heading = {
      sign = false,
      icons = {},
    },
  },
  ft = { "markdown", "norg", "rmd", "org" },
  config = function(_, opts)
    require("render-markdown").setup(opts)
    LazyVim.toggle.map("<leader>um", {
      name = "Render Markdown",
      get = function()
        return require("render-markdown.state").enabled
      end,
      set = function(enabled)
        local m = require("render-markdown")
        if enabled then
          m.enable()
        else
          m.disable()
        end
      end,
    })
  end,
}
```

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
Ah, I wasn't aware of any languages that set backgrounds, makes sense for git diffs.

The only thing we can really do is disable highlighting code blocks for relevant langauges.

Added support for this here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/9725df2306409a836a142244c9eabde96268d730

The default adds `diff` as a disabled language, if you update it should work.

Thanks!
