### ISSUE TITLE
bug: The configuration is not parsed correctly

### ISSUE THREAD

**Issue by mweisshaupt1988** [MeanderingProgrammer/markdown.nvim#111]
### Neovim version (nvim -v)

0.10.2

### Operating system

Linux

### Terminal emulator / GUI

Kitty

### Describe the bug

I have installed this plugin via vim-plug and since updating the plugin last friday or thursday it does not seem to respect my configuration any more.

I have noticed that if I source my plugins.lua file again in which the configuration is located, then it applies it so it seams there is something wrong in the initial parsing.

### Expected behavior

Apply the selected configuration options without having to manually execute the configuration again.

### Healthcheck output

render-markdown: require("render-markdown.health").check()

markdown.nvim [neovim version] ~
- OK Version >= 0.10

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- OK latex: parser installed

markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

### Plugin configuration

```lua
vim.call('plug#begin', '~/.config/nvim/plugged')
-- Other plugins ommitted
Plug 'https://github.com/MeanderingProgrammer/markdown.nvim.git'
vim.call('plug#end')

require('render-markdown').setup({
    bullet = {
        -- icons = { '', '󰨐', '', '' },
        icons = { '', '', '', '' },
    },
    code = {
        border = 'thin',
        style = 'normal',
        sign = false,
        left_pad = 1,
        right_pad = 1,
    },
    heading = {
        backgrounds = {
            'Normal',
            'Normal',
            'Normal',
            'Normal',
            'Normal',
            'Normal',
        },
        foregrounds = {
            'MarkdownHeader',
            'MarkdownHeader',
            'MarkdownHeader',
            'MarkdownHeader',
            'MarkdownHeader',
            'MarkdownHeader',
        },
    },
})
```

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

### Additional information

I believe this is related to the plugin manager that is used, lazy and packer operate somewhat different but I think plugins should be usable with any plugin manager.

**Comment by MeanderingProgrammer** [comment]
Huh, that is strange.

I imagine the problem came from this commit: https://github.com/MeanderingProgrammer/markdown.nvim/commit/67bdd9b68c6519bf1d5365f10c96107032bb4532, where I moved initialization into the `plugin` directory.

I'm not much of an expert on initialization order so am making some assumptions. I believe this issue occurs because the logic in the `plugin` directory runs AFTER your call to `setup`, which would clobber the configuration. Do you know if that is the case and if there are any docs for why this happens?

In the mean time I'll see if I can fix assuming this is the problem.

**Comment by MeanderingProgrammer** [comment]
Have pushed a change that I believe should fix this: https://github.com/MeanderingProgrammer/markdown.nvim/commit/4539c1a5d5f961c11bfee7622aa127f4b8a1de16.

Can you update the plugin and see if the configuration gets picked up now?

**Comment by mweisshaupt1988** [comment]
Yes it works again now, thank you for the fix :)
