### ISSUE TITLE
bug: invalid column error when openning some markdown files

### ISSUE THREAD

**Issue by jdhao** [MeanderingProgrammer/markdown.nvim#112]
### Neovim version (nvim -v)

0.10.1

### Operating system

macOS

### Terminal emulator / GUI

wezterm

### Describe the bug

When I open the following markdown file, I see invalid col error constantly.

[firenvim.md](https://github.com/user-attachments/files/16472257/firenvim.md)

### Expected behavior

I can view this file without errors.

### Healthcheck output

render-markdown: require("render-markdown.health").check()

markdown.nvim [neovim version] ~
- OK Version >= 0.10

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

### Plugin configuration

you can reproduce with the following `mini.lua` (`nvim -u mini.lua firenvim.md`)

```
local plugin_dir = vim.fn.stdpath("data") .. "/lazy"
local lazypath = plugin_dir .. "/lazy.nvim"

if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  }
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  spec = {
    {
      "MeanderingProgrammer/markdown.nvim",
      main = "render-markdown",
      opts = {},
      dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },
    },
  }
}
)

```

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
Hmm, I'm unable to reproduce this with the minimal init and example file.

It may be an issue with an older version of this plugin. Just to double check can you update the plugin and see if the error still occurs?

**Comment by MeanderingProgrammer** [comment]
I've pushed a change to remove any strictness checks, should prevent these errors from being surfaced to users.

**Comment by jdhao** [comment]
hey, thanks! Seems that your latest update fixed the invalid col error.
