### ISSUE TITLE
bug: Callouts on wrapped lines

### ISSUE THREAD

**Issue by avih7531** [MeanderingProgrammer/markdown.nvim#114]
### Neovim version (nvim -v)

0.10.1

### Operating system

Arch Linux

### Terminal emulator / GUI

WezTerm

### Describe the bug

The line for wrapped callouts should continue with the wrapped line:
![Current Behavior](https://github.com/user-attachments/assets/6d07dcb7-8750-45f9-a62a-da87132e6b61)

```
> [!caution] StarWars
> A long time ago in a galaxy far, far away.... BUM BUUUM BUM BUM BUM BUUUUM BUM BUM BUM BUM BUUUUUUUM BUM BUM BUM BUM.
```

(Yes I know I missed a 'bum', yes it is embarrassing)

### Expected behavior

The line should continue onto the wrapped line

### Healthcheck output

```
==============================================================================
render-markdown: require("render-markdown.health").check()

markdown.nvim [version] ~
- OK plugin 5.1.0
- OK neovim >= 0.10

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- OK latex: parser installed

markdown.nvim [executables] ~
- OK latex2text: installed

markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```

### Plugin configuration

```
return {
  'MeanderingProgrammer/markdown.nvim',
  ft = { 'markdown' },
  dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.nvim' },
  config = function()
    require('render-markdown').setup({})
  end,
}
```

### Confirmations

- [x] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

### Additional information

No, thank you :)

**Comment by MeanderingProgrammer** [comment]
Have added this feature here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/66110ddfc27b8785f3046dcf516a4f75d6a8f0f9

Unfortunately because line breaks have a lot of ways to configure behavior I can't guarantee it will work well so have it disabled by default. If you don't set any options it will end up obscuring the text underneath the mark.

You can use the `win_options` setting for this plugin to avoid touching your global options. Here is an example config that seems to work for all callouts / block quotes that I tried:

```lua
require('render-markdown').setup({
    quote = { repeat_linebreak = true },
    win_options = {
        showbreak = { default = vim.api.nvim_get_option_value('showbreak', {}), rendered = '  ' },
        breakindent = { default = vim.api.nvim_get_option_value('breakindent', {}), rendered = true },
        breakindentopt = { default = vim.api.nvim_get_option_value('breakindentopt', {}), rendered = '' },
    },
})
```

**Comment by greyHairChooseLife** [comment]
@avih7531 

Sorry but, just out of curiosity, how could you get that colored text after subject line?

**Comment by avih7531** [comment]
> @avih7531
> 
> Sorry but, just out of curiosity, how could you get that colored text after subject line?

Catppuccin theme!
