### ISSUE TITLE
Render the checkmark without the bullet point

### ISSUE THREAD

**Issue by olivertzeng** [MeanderingProgrammer/markdown.nvim#18]
● - [x] checkmark should be shown without the bullet point
- [x] In other words it should be this instead

**Comment by MeanderingProgrammer** [comment]
Yeah, this has to do with `list-marker` queries also resolving when before checkboxes.

Can probably do something with the query to avoid placing a bullet when before a checkbox, but having it "disappear" might be more tricky.
