### ISSUE TITLE
Does this plugin support syntax highlighting in ```code blocks```?

### ISSUE THREAD

**Issue by YousufSSyed** [MeanderingProgrammer/markdown.nvim#27]

**Comment by MeanderingProgrammer** [comment]
Yes, but its not really a feature of this plugin, just the behavior of tree sitter in markdown files.

You do need to provide the language at the start of the code block, since inferring the language in the code block is not possible. i.e. ```python, to get python highlights in the block. You also need to have that language parser installed.

If you are providing a language at the start of a code block and have the parser installed and highlights are still not working let me know.

Note this does not work for inline code blocks since a language cannot be specified.
