### ISSUE TITLE
What icons are being used as the defaults?

### ISSUE THREAD

**Issue by Senjai** [MeanderingProgrammer/markdown.nvim#29]
I'm on a macbook if it helps, but the icons both listed in github and the defaults are coming up as the unicode box character, is there an iconset or font you have installed to make these work correctly? I'm currently using Fira code.

**Comment by MeanderingProgrammer** [comment]
Any nerd font should do. Or a terminal like Wezterm which is able to do fallback fonts and comes with a nerd font fallback built in. 

If you use icons in Neovim this should just kinda work. 

All the icons are user configurable so you are also able to provide your own that work with your font in the call to setup, if you prefer not to change fonts.

**Comment by Senjai** [comment]
ty!
