### ISSUE TITLE
How to use with custom file type, e.g Octo.nvim?

### ISSUE THREAD

**Issue by lkhphuc** [MeanderingProgrammer/markdown.nvim#33]
I'm trying to use this plugin with Octo.nvim for editing GH's issue. They create a file with type 'octo' so I tried to add to the list of filetype like this:
```
  {
    "MeanderingProgrammer/markdown.nvim",
    dependencies = { { "headlines.nvim", enabled = false } },
    name = "render-markdown", -- Only needed if you have another plugin named markdown.nvim
    ft = { "markdown", "python", "quarto", "rmd", "vimwiki", "norg", "org", "octo" },
    opts = {
      file_types = { "markdown", "python", "quarto", "rmd", "vimwiki", "norg", "org", "octo" },
    },
  },

```
but I receive error `no parser for octo`.

Is there some configuration that I'm missing?

**Comment by MeanderingProgrammer** [comment]
In the FAQ for octo: https://github.com/pwntester/octo.nvim?tab=readme-ov-file#-faq

There is a section: `Can I use treesitter markdown parser with octo buffers?`

Solution seems to be to add this line somewhere in your config:

```lua
vim.treesitter.language.register('markdown', 'octo')
```

LMK if that fixes things for you!

**Comment by lkhphuc** [comment]
Ah that worked, somehow I missed that. Thank you.
