### ISSUE TITLE
Custom head1 emoji can't attach a empty space

### ISSUE THREAD

**Issue by xixiaofinland** [MeanderingProgrammer/markdown.nvim#35]
When customizing heads' and bulletpoints' emoji icons, H1 and bullet points can't use "a space" after the icon, like my current config [here](https://github.com/xixiaofinland/dotfiles/blob/2f6f1b4fb240cffcb97d9731de52942308438bf3/.config/nvim/lua/plugins/markdown.lua#L6)

Taking H1 as an example, if I add the space after the icon (i.e. '🐹 ' rather than '🐹'),  the first char ('f') after the H1 is overlapped (screenshot below)
![Image 007](https://github.com/MeanderingProgrammer/markdown.nvim/assets/13655323/3e946c22-b65d-457b-b116-02ffbc566ea0)

Here is the text version
![Image 008](https://github.com/MeanderingProgrammer/markdown.nvim/assets/13655323/b5c0f669-bdb7-46be-a1d6-fd80daf65966)

This issue doesn't apply to H2, H3....

**Comment by MeanderingProgrammer** [comment]
Yeah, this is due to the number of characters we have on an h1. Since it's only the single `#` and the space, there are only 2 characters available to us before we start overwriting the title. Some more details on it here: https://github.com/MeanderingProgrammer/markdown.nvim/issues/12#issuecomment-2035556921.

**Comment by xixiaofinland** [comment]
I see, thanks for the explanation. I agree it's better to keep it simple and not mess up with the original text.

**Comment by MeanderingProgrammer** [comment]
I did push a fix for this here https://github.com/MeanderingProgrammer/markdown.nvim/commit/5ce35662725b1024c6dddc8d0bc03befc5abc878, if you want to try using longer icons / text and are using neovim >= `0.10.0`.

**Comment by xixiaofinland** [comment]
Thanks for notifying! I will give it a try
