### ISSUE TITLE
Feat: Command to switch to source mode while in normal mode. 

### ISSUE THREAD

**Issue by Feel-ix-343** [MeanderingProgrammer/markdown.nvim#4]
Sometimes I want to see the source in normal mode.

**Comment by MeanderingProgrammer** [comment]
Seems reasonable enough

**Comment by MeanderingProgrammer** [comment]
Added feature in: https://github.com/MeanderingProgrammer/markdown.nvim/commit/fea6f3de62d864633ffe4e1e0fd92d1e746f77ed

Can use RenderMarkdownToggle user command or hookup a keymap to the `require('render-markdown').toggle()` function.
