### ISSUE TITLE
bug: Callouts render incorrectly for "quote-paragraphs"

### ISSUE THREAD

**Issue by Townk** [MeanderingProgrammer/markdown.nvim#41]
### Neovim version (nvim -v)

0.10.0

### Operating system

macOS

### Terminal emulator / GUI

Kitty 0.35.1

### Describe the bug

Callouts render perfect when they are made on a contiguous sequence of text:

![CleanShot 2024-06-22 at 13 07 18](https://github.com/MeanderingProgrammer/markdown.nvim/assets/1261/256ff47c-1605-44f8-9f9a-6378c3cae99e)

But, as soon as the quotation adds paragraphs to it, the rendering is broken:

![CleanShot 2024-06-22 at 13 09 04](https://github.com/MeanderingProgrammer/markdown.nvim/assets/1261/f9d76d00-0098-46c5-ab27-41f1d62ccf1f)

I tried to play around with the TreeSitter query to see if I could fix it in my configuration, but my lack of knowledge in that area held me down :P 

### Expected behavior

The plugin should render the left-side bar on the entire quotation when it is a callout.

**Comment by MeanderingProgrammer** [comment]
Hi, thanks for bringing this up!

Should be resolved by: https://github.com/MeanderingProgrammer/markdown.nvim/commit/6f64bf645b817ff493a28925b1872a69d07fc094

Please update and lmk if it works as expected!

**Comment by Townk** [comment]
Yep, I can confirm the issue is solved with the commit you linked. Thank you so much for the quick response!
