### ISSUE TITLE
bug: Incorrect language selector for code blocks

### ISSUE THREAD

**Issue by sergey-tikhonenko** [MeanderingProgrammer/markdown.nvim#44]
### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713484068

### Operating system

Linux, Ubuntu 22.04.4 LTS

### Terminal emulator / GUI

kitty 0.21.2

### Describe the bug

The plugin doesn't support all forms of the language specification for code blocks that are supported by the Markdown Treesitter parser.

![изображение](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2196190/3974d766-4666-457d-8991-1f6c0d4f05b5)

The language selector [here](https://github.com/MeanderingProgrammer/markdown.nvim/blob/0d6ebe032367eb77082d28585c7872e93f88df01/lua/render-markdown/handler/markdown.lua#L74) should be `(info_string (language))` instead of `(info_string)`.

![изображение](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2196190/11fc9ff0-6cec-4f5a-bc3a-1037af9510da)

![изображение](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2196190/96945091-22a3-42fa-9e00-3bdde5f84d4b)

The Treesitter markdown parser explicitly identifies the separate language node in the AST, leaving the surroundings unspecified.

See also the snippet below with several options for specifying the code block language:

The ordinary code block with the short form language.
```python
```python
print("Hello")
```

Code blocks that use braces around the language name (e.g. ````{python}`) are executable, and will be run by [Quarto](https://quarto.org/docs/computations/python.html) during render. Treesitter supports this form.
```{python}
```{python}
1 + 1
```
![изображение](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2196190/a0c26ec8-9823-4dd2-b7de-35230e9eeb0f)

This is code block with the short form language and separate attributes. Treesitter supports this form.
```python  {.numberLines filename="hello.py"}
```python  {.numberLines filename="hello.py"}
print("Hello")
```
![изображение](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2196190/daf7bb7e-7927-4c38-9c62-b13b6c975bf3)

This code block with the [Pandoc form](https://pandoc.org/MANUAL.html#extension-fenced_code_attributes) language and attributes. At the moment Treesitter doesn't recognise the language for this form.
```{.python  .numberLines filename="hello.py"}
```{.python  .numberLines filename="hello.py"}
print("Hello")
```
![изображение](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2196190/98cd4270-fc96-40ba-b5b9-1ebc2f27680b)

### Expected behavior

The plugin for language detection should use the `(info_string (language))` selector instead of `(info_string)`.

### Additional information

The functionality was added during the "Feature: add language icon for code block" (6eef62c) implementation.

**Comment by MeanderingProgrammer** [comment]
That makes sense, was not even aware of all of these options for code blocks, neat!

Have pushed a fix here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/90072fdbc28042add4cd08bef282df032bf6ac42.

LMK how it works!

**Comment by sergey-tikhonenko** [comment]
Works as expected. Thanks.

![изображение](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2196190/7dc9494f-13da-42bb-ac48-d88e38ca904c)

Ideally it might display the filename next to the language, but this requires the Markdown Treesitter parser support for the attribute map.

**Comment by MeanderingProgrammer** [comment]
Do have any special conceal logic removing the attribute map?

For me the attribute map stays in the 3rd example, like in this demo: https://github.com/MeanderingProgrammer/markdown.nvim/blob/main/demo/heading_code.gif

**Comment by sergey-tikhonenko** [comment]
Thanks for the question.

I thought it was your plugin that conceals attributes, but there were my custom Treesitter rules. This was an attempt to conceal the curly braces around the language while there are no other attributes.
```scheme
; hide curly braces for quatro files
 (fenced_code_block
   (info_string) @label
   (#set! conceal ""))
```
But this doesn't work if any attributes are specified.

Not sure if conditions are supported in the Treesitter rules. Need to checked, if not, then only a custom handler can help in the case.

![изображение](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2196190/b84ac9bc-6e77-4736-a0f5-cff951eaad57)

**Comment by sergey-tikhonenko** [comment]
LazyVim replaces `nvim-tree/nvim-web-devicons` with `echasnovski/mini.icons`. This give better integrations (more languages).
There are also defaults for unknown languages, so the language name does not disappear in the above mentioned cases.

![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2196190/ae400d0f-5758-428d-8827-7c5fec1dbed9)

**Comment by sergey-tikhonenko** [comment]
LazyVim replaces `nvim-tree/nvim-web-devicons` with `echasnovski/mini.icons`. This give better integrations (more languages).
There are also defaults for unknown languages, so the language name does not disappear in the above mentioned cases.

![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2196190/ae400d0f-5758-428d-8827-7c5fec1dbed9)

**Comment by MeanderingProgrammer** [comment]
Thanks for the heads up!

Added support for `mini.icons` here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/353e4459938dd58873772e27a45c1d92bc83bafc.

Gets used instead of `nvim-web-devicons` when its available.

**Comment by sergey-tikhonenko** [comment]
Just for a feedback.

Finally, I've got a configuration that satisfy my needs for now. To hide the curly braces, I have to write a small custom handler:
```lua
custom_handlers = {
  markdown = {
    -- hides curly braces around the language line for code blocks
    render = function(namespace, root, buf)
      local query = vim.treesitter.query.parse("markdown", "(info_string) @_info")
      for _, node in query:iter_captures(root, buf) do
        local value = vim.treesitter.get_node_text(node, buf)
        local start_row, start_col, end_row, end_col = node:range()
        local start_match, _, start_meta, end_meta = string.find(value, "^%s*{%s*().*()%s*}%s*$")
        if start_match then
          vim.api.nvim_buf_set_extmark(buf, namespace, start_row, start_col, {
            end_row = start_row,
            end_col = start_col + start_meta - 1,
            conceal = "",
          })
          vim.api.nvim_buf_set_extmark(buf, namespace, end_row, start_col + end_meta - 1, {
            end_row = end_row,
            end_col = end_col,
            conceal = "",
          })
        end
      end
    end,
    extends = true,
  },
},
```
Might be this will be useful for someone.

![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2196190/ff847df4-7fd2-4381-ba5b-71bd37355a1b)

**Comment by sergey-tikhonenko** [comment]
In 90072fd you use `virt_text_pos = 'inline'` relying on [default](https://github.com/neovim/neovim/blob/master/runtime/queries/markdown/highlights.scm#L63) highlighting NeoVim configuration for markdown. Where the language node is concealed.

I've faced with an environment where user has his own `~/.config/nvim/queries/markdown/highlights.scm` due to conceal directives can't be reverted. And, among other things, concealment of the the language node is not enabled.

Enabling the plugin in such environment results in duplication in the language name.

![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2196190/45abc85e-4da0-4f99-964e-58d7be831516)

I don't know how it might be fixed without change users highlights.scm. Possible some check for region concealment. Don't have enough experience in Neovim machinery.

**Comment by MeanderingProgrammer** [comment]
Yeah, that is definitely a growing trend of issues.

I'm going to track that here: https://github.com/MeanderingProgrammer/markdown.nvim/issues/50, see if I can think of a reasonable approach to it.
