### ISSUE TITLE
Change color of Headings

### ISSUE THREAD

**Issue by liston** [MeanderingProgrammer/markdown.nvim#48]
Not really an issue, but it is not obvious to me looking at the documentation on how to change the colors of h1, h2, h3 etc.

**Comment by MeanderingProgrammer** [comment]
Ah, I'll work on a better layout to explain what to edit to have what effect.

In this particular case you would provide `highlights` -> `heading` -> `backgrounds` / `foregrounds`.

The highlight for `backgrounds` is used for the line and `foregrounds` is used for the text.

The plugin indexes into the lists based on the level, so h4's get the 4th element. If you provide fewer elements we simply use the last one. So if you provide 3 elements we use the 3rd for an h4.

Hope that makes sense!

**Comment by MeanderingProgrammer** [comment]
Thank you :)

2 things:

1. I'm a little lost on how you're getting the results in your video. Mostly in that some of your headings are full width, like the green and blue stretch across the entire window, and some of them end at the edge of the text. They should definitely be consistently one or the other, either all full width or all text width. It might be another plugin clashing, if you're using `obsidian.nvim` for example its own UI logic might be interfering here: https://github.com/MeanderingProgrammer/markdown.nvim?tab=readme-ov-file#obsidiannvim. I added some known clashing plugins to the healthcheck if you update and run `checkhealth render-markdown` it might help with that and likely other weird issues that will happen as a result.
2. When you hover over a line all the virtual text and highlights added by my plugin go away, leaving you with the default view for that line. For headings tree-sitter will set the following highlight groups: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#markup. From there if you use a colorscheme it will most likely provide a value for this highlight group. But if you don't like it you can either try a different colorscheme or manually override the value for the various `@markup.heading.n.markdown` highlights in the same way you set them in the config: `vim.cmd(string.format([[highlight @markup.heading.1.markdown cterm=bold gui=bold guifg=%s]], color_fg))`, for example.

**Comment by linkarzu** [comment]
- Hey, regarding item 1, I don't use obsidian and I also have the headlines plugin disabled, I used that before, but I replaced it for this plugin
  - I use folds a lot, so when a section is folded, that's how headings look, shortened, not sure why, the ones that show the full length are the ones that are not folded
  - here's my `checkhealth render-markdown` output (not sure what those errors mean though):
```lua
render-markdown: require("render-markdown.health").check()

markdown.nvim [neovim version] ~
- OK Version >= 0.10

markdown.nvim [configuration] ~
- ERROR render-markdown.heading.1: is not a valid key
- ERROR render-markdown.heading.2: is not a valid key
- ERROR render-markdown.heading.3: is not a valid key
- ERROR render-markdown.heading.4: is not a valid key
- ERROR render-markdown.heading.5: is not a valid key
- ERROR render-markdown.heading.6: is not a valid key
- ERROR render-markdown.heading.7: is not a valid key
- ERROR render-markdown.heading.8: is not a valid key
- ERROR render-markdown.heading.9: is not a valid key
- ERROR render-markdown.heading.10: is not a valid key
- ERROR render-markdown.heading.11: is not a valid key
- ERROR render-markdown.heading.12: is not a valid key

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed
```
- Regarding item 2, thanks for letting me know that when I hover over a line, your plugin goes away, I tried to override the highlights with an autocommand, wasn't able to, si just loaded those highlights after loading everything and now I was able to set them properly. I really appreciate the help.

![linkarzu com 2024-07-25 at 09 39 13](https://github.com/user-attachments/assets/dbf029fd-85fc-4e72-acce-984e1d99f467)
