### ISSUE TITLE
issues with indenting

### ISSUE THREAD

**Issue by Feel-ix-343** [MeanderingProgrammer/markdown.nvim#5]
![markdownnvim](https://github.com/MeanderingProgrammer/markdown.nvim/assets/88951499/29c1883f-cb9e-4d86-b6c0-29c6266f74a7)

I think you may assume 2 space indent level

**Comment by MeanderingProgrammer** [comment]
While I don't assume a 2 space indent I did assume tree-sitter would always return list items with any leading spaces removed, hoping it would take care of whatever level of nesting. This does not appear to be the case though :(

Thanks for reporting this!

**Comment by MeanderingProgrammer** [comment]
Appears to be a known issue with the underlying parser: https://github.com/tree-sitter-grammars/tree-sitter-markdown/issues/127

**Comment by Feel-ix-343** [comment]
I sent you an email too btw ;)

**Comment by MeanderingProgrammer** [comment]
> I sent you an email too btw ;)

Sorry am bad at checking my email will get to it shortly!

**Comment by MeanderingProgrammer** [comment]
Issue should be resolved by: https://github.com/MeanderingProgrammer/markdown.nvim/commit/df98da81375e5dc613c3b1eaa915a847059d48d9

**Comment by Feel-ix-343** [comment]
Incredible!

**Comment by Feel-ix-343** [comment]
works.
