### ISSUE TITLE
question: How can I remove background of code block

### ISSUE THREAD

**Issue by realhackcraft** [MeanderingProgrammer/markdown.nvim#52]
I want to remove the background color for the code block, since I have a transparent terminal setup.

**Comment by realhackcraft** [comment]
I would like the syntax highlighting and the language name + icon, just no background.

**Comment by MeanderingProgrammer** [comment]
Was not supported before. 

Added this feature here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/308f9a826e371e33512234e4604cf581fe1d4ef8.

Please update the plugin and set the following:

```lua
require('render-markdown').setup({
    code = { style = 'language' },
})
```

**Comment by realhackcraft** [comment]
Thank you!

**Comment by realhackcraft** [comment]
With this fix, I've noticed that the background for the langauge icon and name is stills there. Also unrelated, I would also like it if inline code didn't have the background as well.

**Comment by realhackcraft** [comment]
<img width="551" alt="Screenshot 2024-07-08 at 20 59 42" src="https://github.com/MeanderingProgrammer/markdown.nvim/assets/65378120/4f3a9d1c-7622-43e2-9d27-6607e00ae8a7">

<img width="72" alt="Screenshot 2024-07-08 at 20 59 54" src="https://github.com/MeanderingProgrammer/markdown.nvim/assets/65378120/bcd2a8c9-6c3a-42cb-a374-641c0581e18a">

**Comment by MeanderingProgrammer** [comment]
Ah, fair enough!

Updated the behavior of code style here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/e19ed93d75216f8535ede4d401e56ef478856861

Should accomplish both of these.

**Comment by realhackcraft** [comment]
Thank you, it works perfectly on my machine now!
