### ISSUE TITLE
bug: The new "boarder" option is spelled wrong. It should be "border"

### ISSUE THREAD

**Issue by kmoschcau** [MeanderingProgrammer/markdown.nvim#54]
### Neovim version (nvim -v)

N/A

### Operating system

N/A

### Terminal emulator / GUI

N/A

### Describe the bug

The config property is spelled "boarder". This might lead to users and maintainers making mistakes when spelling it correctly instead.

### Expected behavior

The config property should be spelled "border".

### Healthcheck output (:checkhealth render-markdown)

N/A

### Additional information

Suggestion: Calling it "borders" might be even better.

**Comment by MeanderingProgrammer** [comment]
Thanks!

I think I've made this same mistake before, haha

Fixed in: https://github.com/MeanderingProgrammer/markdown.nvim/commit/fca29031c0fa16b034741f64a042793dfb105aa2

I did keep it singular, both seemed valid
