### ISSUE TITLE
feature: Add icons to image and link to distinguish them

### ISSUE THREAD

**Issue by MasouShizuka** [MeanderingProgrammer/markdown.nvim#55]
### Is your feature request related to a problem? Please describe.

Currently, both link and image are rendered only as text in `[]`, and there is no way to distinguish between the two:
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/44764707/c0e16755-7c74-43ed-95e9-9c26b6794f41)

### Describe the solution you'd like

Add icons for link and image to distinguish them，like:
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/44764707/c7df405f-d209-4e65-95ec-f07663e1d32a)

### Describe alternatives you've considered

Edit: Or could add highlights of both.

**Comment by MeanderingProgrammer** [comment]
Sure, added here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/501e5e01493204926aa4e2a12f97b7289636b136

LMK if this is what you had in mind!

**Comment by MasouShizuka** [comment]
That's exactly what I wanted, thank you!
