### ISSUE TITLE
feature: add a keyboard shortcut to toggle checkboxes

### ISSUE THREAD

**Issue by eldar** [MeanderingProgrammer/markdown.nvim#56]
### Is your feature request related to a problem? Please describe.

When working witch TODO lists with checkboxes it is convenient to toggle them on and off with a single keyboard shortcut without manually editing the source file.

### Describe the solution you'd like

Introduce the shortcut that would toggle a checkbox on and off while the cursor is positioned anywhere in the line that contains this checkbox. An good example of the desired behavior is Markdown All-in-one extension for VS Code: https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one#keyboard-shortcuts

### Describe alternatives you've considered

The current alternative is to simply edit the document itself which is not as efficient.

**Comment by MeanderingProgrammer** [comment]
I get the idea, but this is primarily meant to be a UI plugin, as opposed to text objects / motions.

What you're looking for fits really well as a feature in: https://github.com/tadmccorkle/markdown.nvim (if it's not already supported).

**Comment by eldar** [comment]
OK, sorry for misunderstanding - I'm very much new to NeoVIM. You are right indeed and markdown.nvim contains the desired ability: https://github.com/tadmccorkle/markdown.nvim?tab=readme-ov-file#toggle-tasks. Thanks for pointing at it!

**Comment by MeanderingProgrammer** [comment]
No worries at all, is a reasonable ask! Happy to help!
