### ISSUE TITLE
feature: add emphasis and strong to inline queries

### ISSUE THREAD

**Issue by georgeharker** [MeanderingProgrammer/markdown.nvim#57]
### Is your feature request related to a problem? Please describe.

The bolded and italicized sections don't render by default

### Describe the solution you'd like

adding
```
inline_query = [[
            (code_span) @code
    
            (shortcut_link) @callout
    
            (inline_link) @link
    
            (image) @image

            (emphasis) @text.emphasis

            (strong) @text.strong
        ]],
```

to the config fixes it - I wonder if they should be there by default?

### Describe alternatives you've considered

Seems like the above is the correct fix.

**Comment by MeanderingProgrammer** [comment]
Feel free to re-open if solutions above do not work for you!
