### ISSUE TITLE
feature: Improve background colors of signs highlight groups

### ISSUE THREAD

**Issue by kmoschcau** [MeanderingProgrammer/markdown.nvim#58]
### Is your feature request related to a problem? Please describe.

Currently it looks like the signs added by this plugin use the background color of the `Normal` highlight group. This leads to effects like this:
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/9497302/31f57344-b7b2-48c2-b6eb-d241cf3fdcfd)

### Describe the solution you'd like

Here are three possible solutions:
- Do not set a background color for the signs.
- Use the background color of the `SignColumn` highlight group instead.
- Provide a way to configure the sign highlight groups separately.

**Comment by MeanderingProgrammer** [comment]
Thanks for bringing this up, that is definitely unexpected.

The signs added by this plugin don't add a background highlight group.

In the case of code we use only the highlight group returned from the icon provider. So in the case of `mini.icons` & `python` we get `MiniIconsYellow` and only set that: https://github.com/MeanderingProgrammer/markdown.nvim/blob/main/lua/render-markdown/handler/markdown.lua#L93-L102.

Then in the case of headings we use only the value of the foreground highlight group: https://github.com/MeanderingProgrammer/markdown.nvim/blob/main/lua/render-markdown/handler/markdown.lua#L43-L60.

In both of these cases we do not add `Normal` as a background.

I've played around with a few other color schemes and am unable to replicate the background being different, though I can clearly see it in your screenshot. What colorscheme do you use?

**Comment by kmoschcau** [comment]
I use my own theme, which I generate with [this lua tool](https://github.com/kmoschcau/nvim-config/blob/main/lua%2Fcolor-tool.lua). I mean there's no such thing really as background and foreground highlight groups. Highlight groups can have both a foreground and background color. If you'd want to make sure to only use the foreground color of an existing highlight, you'd need to extract that from the highlight.

**Comment by MeanderingProgrammer** [comment]
Yeah, I call them `foreground` since the highlights seem to only define `guifg` (at least for me).

Which icon provider are you using?

If it's `mini.icons` then the highlight group for python resolves to `MiniIconsYellow` which for me only has a `guifg` defined.

If it's `nvim-web-devicons` then the highlight group for python resolves to `DevIconPy` which only has `ctermfg` and `guifg` defined.

I'm just rather lost on how a background is getting set on these icons for you. Is there some fallback logic happening somewhere? As far as I'm aware the solution `Do not set a background color for the signs.` is already the case.

**Comment by kmoschcau** [comment]
~~I use `mini.icons`. And I just checked myself: `MiniIconsYellow` only has `guifg` and `ctermfg`.
It's a bit difficult to inspect the final result. I could just use `:Inspect`, if it was in a buffer, but for signs I'd need some other way.~~

I just looked through my tool again and tested a bit: Signs highlight groups do not behave different from other highlight groups. Anything that's not specified for a highlight group falls back to what's specified for `Normal`. Meaning, for signs you have to specifically set the background to match that of the `SignColumn` highlight group. That's what I do for all sign highlights I have defined.

**Comment by MeanderingProgrammer** [comment]
Added the logic to use the SignColumn background here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/d398f3e9f21d88e1de51594cd4a78f56a3a3eb9e

Please update and lmk if it looks better!

Also added the ability to disable signs on specific buftypes, defaults to `nofile`. Will follow up in the other thread with that.

**Comment by kmoschcau** [comment]
Yep, that works like a charm!
![image](https://github.com/user-attachments/assets/d0300262-878f-4366-b329-5cc1966c7fce)
![image](https://github.com/user-attachments/assets/27f7332a-4d0f-4e8a-b6e2-fe058cba68b2)

**Comment by MeanderingProgrammer** [comment]
Sweet! Btw for the optional fields there's an equivalent type called 'render.md.UserConfig'. I have a script to generate one from the other so they stay in sync.

**Comment by kmoschcau** [comment]
Ah! Good to know. I admit it was a subtle attempt to get it fixed or info on how to improve it on my side. 😄 
Thanks again for all the work you put in. This is really a great plugin.
