### ISSUE TITLE
bug: `nvim_buf_set_lines()` causes `Assertion `buf->b_signcols.count[prevwidth - 1] >= 0' failed.`

### ISSUE THREAD

**Issue by oblitzitate** [MeanderingProgrammer/markdown.nvim#59]
### Neovim version (nvim -v)

NVIM v0.11.0-dev-322+ge7020306a Build type: RelWithDebInfo LuaJIT 2.1.1716656478

### Operating system

Linux

### Terminal emulator / GUI

Kitty

### Describe the bug

When I run `nvim_buf_set_lines()` in a function...

```fennel
;; Example
(fn M.set_title [title]
  (local line_count (api.nvim_buf_line_count 0))
  (var done false)
  (for [i 0 (- line_count 1) &until done]
    (local line (. (api.nvim_buf_get_lines 0 i (+ i 1) false) 1))
    (when (line:match "^#%s*(.+)")
      (local heading (.. "# " title))
      (api.nvim_buf_set_lines 0 i (+ i 1) false [heading])
      (set done true))))
```

... I get the following error:

```
nvim: /home/runner/work/neovim/neovim/src/nvim/decoration.c:857: buf_signcols_count_range: Assertion `buf->b_signcols.count[prevwidth - 1] >= 0' failed. 
```

It doesn't cause the error when I disable the rendering.

### Expected behavior

To not cause an error when I run `nvim_buf_set_lines()`.

### Healthcheck output (:checkhealth render-markdown)

```
render-markdown: require("render-markdown.health").check()

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown_inline: parser installed
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }
- OK highlights enabled

markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

markdown.nvim [configuration] ~
- OK valid
```

**Comment by oblitzitate** [comment]
I can workaround this by calling ` vim.api.nvim_buf_clear_namespace()` before `nvim_buf_set_lines()`, but then running **undo** would then cause the error.

**Comment by MeanderingProgrammer** [comment]
How are you running this function? Is it part of an auto command or some user command?

**Comment by oblitzitate** [comment]
The function is part of a user command.

And the language is `Fennel` which transpiles to `Lua`. It's less verbose, but has poor tooling, which I'm fine with since I can workaround this by viewing the lua output file.

**Comment by MeanderingProgrammer** [comment]
I'm going to need a reproducible example, as it definitely has to do with some specific behavior in your user command that I can't trigger on my side and not just `nvim_buf_set_lines` in general.

I added the following commands to my config:

```lua
vim.api.nvim_create_user_command('TestWriteH0', function()
    vim.api.nvim_buf_set_lines(0, 0, 1, false, { 'Test H0' })
end, {})

vim.api.nvim_create_user_command('TestWriteH1', function()
    vim.api.nvim_buf_set_lines(0, 0, 1, false, { '# Test H1' })
end, {})

vim.api.nvim_create_user_command('TestWriteH2', function()
    vim.api.nvim_buf_set_lines(0, 0, 1, false, { '## Test H2' })
end, {})
```

Which overwrite the first line of a file with different headings at different levels.

No matter how I ran them or in what order nothing errors.

**Comment by oblitzitate** [comment]
Found out it occurs when I enable [`luukvbaal/statuscol.nvim`](https://github.com/luukvbaal/statuscol.nvim) or when I have the vim option `statuscolumn` set as `%=%s%{v:relnum?v:relnum:v:lnum}%C`

It seems certain status column config conflict with running `nvim_buf_set_lines()` when texts are concealed? Very odd.

**Comment by MeanderingProgrammer** [comment]
Huh, I am unable to reproduce this behavior with either the plugin or the `statuscolumn` value.

Can you give me a file & a user command that trigger this issue?

**Comment by oblitzitate** [comment]
```fennel
(local api vim.api)

(local M {})

(fn M.rename []
  (M.set_title "Test"))

(fn M.set_title [title]
  (local line_count (api.nvim_buf_line_count 0))
  (var done false)
  (for [i 0 (- line_count 1) &until done]
    (local line (. (api.nvim_buf_get_lines 0 i (+ i 1) false) 1))
    (when (line:match "^#%s*(.+)")
      (local heading (.. "# " title))
      (api.nvim_buf_set_lines 0 i (+ i 1) false [heading])
      (set done true))))
      
(vim.api.nvim_create_user_command
  "MdRename"
  #(M.rename)
  {})
```

The error occurs when running `:MdRename` even after commenting out all vim options except `statuscolumn` and commenting out all plugins except for `lazy.nvim` and `markdown.nvim`.

**Comment by oblitzitate** [comment]
Here's the sample markdown file where having a second heading causes the error:

```markdown
# Heading 1
## Heading 2
```

The error has also occurred when I used another command that uses `nvim_buf_set_text()` to swap a node that contains a checkbox or a node that contains a table.

**Comment by oblitzitate** [comment]
I forgot a crucial part. My config:

```fennel
   {1 "MeanderingProgrammer/markdown.nvim"
    :name "render-markdown"
    :dependencies ["nvim-treesitter/nvim-treesitter"
                   "nvim-tree/nvim-web-devicons"]
    :opts
     {:headings [ "󰼏 " "󰎨 " "󰼑 " "󰎲 " "󰼓 " "󰎴 "]}}
```

Commenting out the `headings` opt prevents the error on that certain command. But it doesn't prevent the error when applying `nvim_buf_set_text()` to nodes with a **checkbox** or a **table**.

A pattern seems to be that the error occurs **when the concealment adjusts the visual position of the text** and you apply `nvim_buf_set_lines()` or `nvim_buf_set_text()` on said text.

**Comment by MeanderingProgrammer** [comment]
Based on your config you're running an older version of this plugin, since headings are now set with:

```lua
{ heading = { icons = { "󰼏 " "󰎨 " "󰼑 " "󰎲 " "󰼓 " "󰎴 " } } }
```

If you update the plugin does the error still happen?

I wrote this version of your user command:

```lua
vim.api.nvim_create_user_command('MdRename', function()
    local line_count = vim.api.nvim_buf_line_count(0)
    for i = 0, line_count - 1 do
        local line = vim.api.nvim_buf_get_lines(0, i, i + 1, false)[1]
        if line:match('^#%s*(.+)') then
            local heading = '# Test'
            vim.api.nvim_buf_set_lines(0, i, i + 1, false, { heading })
            return
        end
    end
end, {})
```

Which I believe should do the same thing, but am unable to get any errors from the sample file.

When you say:

> A pattern seems to be that the error occurs when the concealment adjusts the visual position of the text and you apply nvim_buf_set_lines() or nvim_buf_set_text() on the text?

With headings nothing is concealed (at least by default), so is this an example that doesn't follow the pattern or do you have something concealing the `#` of headings or something to that effect?

**Comment by oblitzitate** [comment]
Yes, I still get the errors.

When I say concealed, I meant the rendering is enabled such as those icons.

Try swapping lines where one of them contains a checkbox item or a table and see if you get errors while you have the `statuscolumn` value and the rendering enabled.

**Comment by MeanderingProgrammer** [comment]
So I set this as my entire config

```lua
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

vim.opt.statuscolumn = '%=%s%{v:relnum?v:relnum:v:lnum}%C'

vim.keymap.set('n', '<A-j>', '<cmd>m .+1<cr>==', { noremap = true, silent = true })
vim.keymap.set('n', '<A-k>', '<cmd>m .-2<cr>==', { noremap = true, silent = true })

vim.api.nvim_create_user_command('Md1', function()
    local line = vim.api.nvim_win_get_cursor(0)[1] - 1
    vim.api.nvim_buf_set_lines(0, line, line + 1, false, { '# Heading 1' })
end, {})

vim.api.nvim_create_user_command('Md2', function()
    local line = vim.api.nvim_win_get_cursor(0)[1] - 1
    vim.api.nvim_buf_set_lines(0, line, line + 1, false, { '- [ ] Unchecked' })
end, {})

vim.api.nvim_create_user_command('Md3', function()
    local line_count = vim.api.nvim_buf_line_count(0)
    for i = 0, line_count - 1 do
        local line = vim.api.nvim_buf_get_lines(0, i, i + 1, false)[1]
        if line:match('^#%s*(.+)') then
            local heading = '# Test'
            vim.api.nvim_buf_set_lines(0, i, i + 1, false, { heading })
            return
        end
    end
end, {})

local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.uv.fs_stat(lazypath) then
    local lazyrepo = 'https://github.com/folke/lazy.nvim.git'
    vim.fn.system({ 'git', 'clone', '--filter=blob:none', '--branch=stable', lazyrepo, lazypath })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
    {
        'MeanderingProgrammer/markdown.nvim',
        config = function()
            require('render-markdown').setup({})
        end,
    },
})
```

Then wrote this markdown file:

```text
# Heading 1
## Heading 2
- [x] Checked
- [ ] Unchecked
```

Here's a recording of what happens as I move lines around and run the various user commands:

![Recording](https://github.com/user-attachments/assets/2be1d76e-11e0-4b93-978e-865c5732a6f8)
