### ISSUE TITLE
bug: Plugin stopped rendering markdown in floating windows (Hover doc) after specific commit

### ISSUE THREAD

**Issue by abulwafa** [MeanderingProgrammer/markdown.nvim#61]
### Neovim version (nvim -v)

0.11.0

### Operating system

Linux

### Terminal emulator / GUI

Kitty

### Describe the bug

First of all, I want to extend my gratitude for creating such an amazing plugin!

I've encountered an issue where the plugin stopped rendering markdown correctly in floating windows, such as Hover doc, after a specific commit. The plugin continues to work perfectly in markdown files themselves.

Steps to Reproduce:

Open a markdown file to confirm the plugin is working.
Use a feature that triggers a floating window (e.g., Hover doc).
Observe that the markdown rendering is not applied in the floating window.

The commit fb7f81e14942ed8814ac5bb26b7cfa90795d21de 

### Expected behavior

The plugin should render markdown with the same quality and visual enhancements in floating windows as it does in markdown files.

### Healthcheck output (:checkhealth render-markdown)

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown_inline: parser installed
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }
- OK highlights enabled

markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

### Additional information

I override the default open float handler, by setting a filetype

```lua
local orig_util_open_floating_preview = vim.lsp.util.open_floating_preview

function vim.lsp.util.open_floating_preview(contents, syntax, opts, ...)
  local bufnr, winnr =
    orig_util_open_floating_preview(contents, syntax, opts, ...)
  vim.api.nvim_set_option_value("signcolumn", "no", { win = winnr })
  vim.api.nvim_set_option_value("filetype", "markdown", { buf = bufnr })
  return bufnr, winnr
end

```
## Before
![20240711_13h27m52s_grim](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2338756/86a492b8-5f64-4f48-9fcd-7a3d43e95fb1)

## After
![20240711_13h29m01s_grim](https://github.com/MeanderingProgrammer/markdown.nvim/assets/2338756/df15fd09-a2ef-4f01-a4ba-5630fa08c6fd)

**Comment by abulwafa** [comment]
Update:
I've figured out the cause of the issue. It was related to a new config option that I had overlooked. After updating my configuration, the plugin works perfectly in both markdown files and floating windows.

```lua
    exclude = {
      -- Buftypes ignored by this plugin, see :h 'buftype'
      buftypes = {"nofile},
    },

```

Thank you once again for your amazing plugin and your support!

**Comment by abulwafa** [comment]
Hi @MeanderingProgrammer,

Thank you for the prompt response and the update!

I can confirm that removing the sign column has made the experience a whole lot better. Rendering the docs and diagnostics using the plugin has significantly improved the readability and usability of the content. Specifically, the ability to conceal URLs in diagnostics is a great feature. It makes the diagnostic messages shorter and more concise, while still allowing the user to open the URLs in a browser when needed.

Once again, thank you for your amazing work

**Comment by kmoschcau** [comment]
Hi, I just found this issue. I'm currently banging my head against the wall, trying to find a way to disable the signcolumn only for hover windows, because I still want to use this plugin in hover windows. @abulwafa have you found a way to do that?

**Comment by abulwafa** [comment]
@kmoschcau Here it is


This line : ` vim.api.nvim_set_option_value("signcolumn", "no", { win = winnr })`


```lua
local orig_util_open_floating_preview = vim.lsp.util.open_floating_preview
function vim.lsp.util.open_floating_preview(contents, syntax, opts, ...)
  local bufnr, winnr =
    orig_util_open_floating_preview(contents, syntax, opts, ...)
  vim.api.nvim_set_option_value("signcolumn", "no", { win = winnr })
  vim.api.nvim_set_option_value("filetype", "markdown", { buf = bufnr })
  return bufnr, winnr
end
```

**Comment by kmoschcau** [comment]
Ah a bit of monkey patching. :D
I was trying to do it via events. But maybe I can achieve something similar with LSP handlers, so that it doesn't affect all floating windows.

**Comment by abulwafa** [comment]
Hi @kmoschcau,

I haven't found a way to override window/buffer options through the `["textDocument/hover"]` handler, the only opts available are: 
```markdown
      • {opts}      (`table?`) with optional fields (additional keys are
                    filtered with |vim.lsp.util.make_floating_popup_options()|
                    before they are passed on to |nvim_open_win()|)
                    • {height}? (`integer`) Height of floating window
                    • {width}? (`integer`) Width of floating window
                    • {wrap}? (`boolean`, default: `true`) Wrap long lines
                    • {wrap_at}? (`integer`) Character to wrap at for
                      computing height when wrap is enabled
                    • {max_width}? (`integer`) Maximal width of floating
                      window
                    • {max_height}? (`integer`) Maximal height of floating
                      window
                    • {focus_id}? (`string`) If a popup with this id is
                      opened, then focus it
                    • {close_events}? (`table`) List of events that closes the
                      floating window
                    • {focusable}? (`boolean`, default: `true`) Make float
                      focusable.
                    • {focus}? (`boolean`, default: `true`) If `true`, and if
                      {focusable} is also `true`, focus an existing floating
                      window with the same {focus_id}
```

You can check for the `syntax` parameter, to only target hover doc

ex. check if `syntax == 'marksown'`

**Comment by MeanderingProgrammer** [comment]
I've made this part of the plugin itself as part of this change: https://github.com/MeanderingProgrammer/markdown.nvim/commit/d398f3e9f21d88e1de51594cd4a78f56a3a3eb9e

Since I needed to globally change the signs the plugin creates anyway

**Comment by kmoschcau** [comment]
@abulwafa the new fix now addresses without any hacks.
![image](https://github.com/user-attachments/assets/27f7332a-4d0f-4e8a-b6e2-fe058cba68b2)

**Comment by abulwafa** [comment]
@MeanderingProgrammer confirmed working as expected
