### ISSUE TITLE
Feature Request: New code block style with reduced padding

### ISSUE THREAD

**Issue by tristan-harris** [MeanderingProgrammer/markdown.nvim#62]
### Is your feature request related to a problem? Please describe.

'Normal' style code blocks have a full line of padding at both ends and can look ugly.

### Describe the solution you'd like

An added code block style that uses half block characters at the borders so that padding is reduced.

![after](https://github.com/MeanderingProgrammer/markdown.nvim/assets/53396419/ea4e1c34-a30f-4f4c-87de-1dfc61edcbb4)

### Describe alternatives you've considered

N/A

### Additional information

Thank you for the work you have put into this plugin, I can't imagine going back to just raw Markdown.

**Comment by tristan-harris** [comment]
Thank you for your response, I'll clarify what I mean.

The code block will still occupy the same number of lines, but two lines will be saved by being able to place text immediately above and below the code block without the border of the code block touching said text.

It's a minor aesthetic thing, but the idea is to allow for more condensed markdown notes while still maintaining clear visual separation between blocks of code and text.

**Comment by MeanderingProgrammer** [comment]
Merged in: https://github.com/MeanderingProgrammer/markdown.nvim/commit/3114d708283002b50a55be0498668ef838b6c4cf

Please update and LMK if it's what you had in mind!

**Comment by tristan-harris** [comment]
Yes this is what I had in mind, thank you for implementing my request.
