### ISSUE TITLE
feature: disable marks?

### ISSUE THREAD

**Issue by juanolon** [MeanderingProgrammer/markdown.nvim#64]
### Is your feature request related to a problem? Please describe.

Since the new update (thanks btw!!), headers displays a mark on the side. How can i disable them? Is it enough to set the `heading.signs` setting to ""?

### Describe the solution you'd like

A way to disable marks for headers.

### Describe alternatives you've considered

setting `heading.signs` to ""? or a flag?

**Comment by MeanderingProgrammer** [comment]
Ah, fair point. Thanks for brining it up!

Have made a change to allow signs to be disabled at a component level: https://github.com/MeanderingProgrammer/markdown.nvim/commit/9b771cc485677f1aa5873642e33a3522b270225d.

So now you can do:

```lua
require('render-markdown').setup({
    heading = { sign = false },
})
```

Depending on what you're trying to accomplish all signs can be disabled using the top level `sign` setting, more info on that here: https://github.com/MeanderingProgrammer/markdown.nvim?tab=readme-ov-file#signs.

Please update and LMK if it works!

**Comment by juanolon** [comment]
Thanks, it works like a charm. That was so quick, i didn't hat time to answer. Thanks!
