### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by devboy** [MeanderingProgrammer/markdown.nvim#67]
### Neovim version (nvim -v)

v0.10.0

### Operating system

MacOS

### Terminal emulator / GUI

Wezterm

### Describe the bug

Checkboxes renders are "eating" up the first two characters of text.
![Screenshot 2024-07-17 at 08 06 46](https://github.com/user-attachments/assets/f1ac642f-adb8-4582-8d38-8dfea64ae2d3)
![Screenshot 2024-07-17 at 08 06 40](https://github.com/user-attachments/assets/b807b334-e3b5-425a-8993-4b693010b4ac)

### Expected behavior

Checkboxes should show the full text.

### Healthcheck output (:checkhealth render-markdown)

==============================================================================
render-markdown: require("render-markdown.health").check()

markdown.nvim [neovim version] ~
- OK Version >= 0.10

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown_inline: parser installed
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }
- OK highlights enabled

markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

**Comment by devboy** [comment]
Looks like this is an issue only in combination with obsidian.nvim. Will close.

**Comment by rstacruz** [comment]
I can confirm this is an issue happening when used with obsidian.nvim. Anyone know of a workaround?

Currently I use `{ ui = { enable = false } }` on obsidian.nvim's options, which fixes this, but wikilinks are no longer displayed properly.
