### ISSUE TITLE
Ability to preview images

### ISSUE THREAD

**Issue by atticus5** [MeanderingProgrammer/markdown.nvim#68]
### Is your feature request related to a problem? Please describe.

I would like to be able to preview the images specified in the Markdown file.

### Describe the solution you'd like

I've seen there is a nvim plugin able to render images [image.nvim](https://github.com/3rd/image.nvim)

### Describe alternatives you've considered

None.

**Comment by mixtli** [comment]
FYI, images just work for me fine in kitty using 3rd/image.nvim

**Comment by MeanderingProgrammer** [comment]
As mentioned above `image.nvim` should just work if you have it setup.

I will not be integrating this plugin directly, nor is there going to be an attempt to format the images.

But from what I've tested locally the 2 plugins should co-exist well enough.

Will add a note about image support to the README.
