### ISSUE TITLE
feature: Different colors for italics and bold

### ISSUE THREAD

**Issue by moonlinx** [MeanderingProgrammer/markdown.nvim#69]
### Is your feature request related to a problem? Please describe.

Currently, whenever I use _italics_ or **bold**, they are the same color and a little difficult to tell apart.

### Describe the solution you'd like

 Is there any way that this can be added to where they are separate colors? OR if there is a way, please let me know. 

### Describe alternatives you've considered

I've looked around the code trying to see if maybe the highlights or something else has to be changed, but I am not coder so I'm not the best at it.

### Additional information

If there is anything I can do to help, I will gladly do so

**Comment by scottmckendry** [comment]
Your coloscheme will need to support different colors for these two highlight groups:
- `@markup.strong`
- `@markup.italic`

As far as I can tell, markdown.nvim doesn't change these at all. Here is what [cyberdream.nvim](https://github.com/scottmckendry/cyberdream.nvim) looks like:
![image](https://github.com/user-attachments/assets/32c043a6-b155-43be-9118-0541b61a79b6)

Chances are your colorscheme allows overriding default highlights. You should be able to set your preferred colors for the two groups I mentioned above in your colorschemes `setup()` function.

**Comment by MeanderingProgrammer** [comment]
The previous comment by @scottmckendry is the correct approach to this. There are 3 ways you can do this, but none of them would live within this plugin:

1. Using a colorscheme that changes `@markup.strong` and `@markup.italic` to your liking, most just set the bold / italic property and do not change the color, but `cyberdream` is an example of one that does change the color.
2. Configuring your colorscheme to set the color for those highlight groups, if supported, some colorscheme plugins let you provide color overrides for specific groups in the `setup` call.
3. Within your config modify those highlight groups using standard `vim.api` calls after your colorscheme is loaded to your liking.

Appreciate the offer and understand the idea, just think in this case managing this elsewhere is a good idea.

**Comment by moonlinx** [comment]
Thank you both. I will take a look into this!
