### ISSUE TITLE
feature: Highlight groups

### ISSUE THREAD

**Issue by scottmckendry** [MeanderingProgrammer/markdown.nvim#70]
### Is your feature request related to a problem? Please describe.

There is currently no easy way for colorsheme maintainers to add support for this plugin. While the defaults are sensible, there are a few things one might like to change to give the best out-of-the-box experience without users having to make too many changes in the config. 

### Describe the solution you'd like

Each component currently has one or more "highlight` properties that use either tree-sitter groups or a default Neovim highlight group.

What I propose is to define new highlight groups in the plugin that link to the existing highlights. This can be executed somewhere in the plugin's `setup()` logic.

For example, for headings, you might add something to the effect of:

```lua
vim.api.nvim_set_hl(0, "RenderMarkdownHeading1", { link = "@markup.heading.1.markdown", default = true })
vim.api.nvim_set_hl(0, "RenderMarkdownHeading2", { link = "@markup.heading.2.markdown", default = true })

vim.api.nvim_set_hl(0, "RenderMarkdownHeading1Bg", { link = "DiffAdd", default = true })
vim.api.nvim_set_hl(0, "RenderMarkdownHeading2Bg", { link = "DiffChange", default = true })
```

`default = true` is important here as it preserves the current setting if the highlight group is already defined somewhere else (like in a colorscheme 😉)

The naming convention I've used in the example is just a suggestion. Feel free to use whatever you see fit - the namespace is global so unique-ness is important.

Using links keeps the current highlight groups the same for existing users, so no breaking changes should be expected. But it allows colorschemes to adopt their own styling should they choose to add support in the future. 

### Describe alternatives you've considered

N/A

### Additional information

For a good example of how to define many highlight groups at once, I recommend looking at Folke's implementation in trouble.nvim:
https://github.com/folke/trouble.nvim/blob/main/lua/trouble/config/highlights.lua

**Comment by MeanderingProgrammer** [comment]
Proposal makes sense to me, the idea of setting a `default = true` link to allow color schemes to override the value is neat. Super simple and powerful.

I implemented it here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/0f3265556abf4076170ac0b6a456c67d814ece94, and used the `RenderMarkdown` prefix as suggested.

Added a table with all of the highlights and their defaults to the README as well: https://github.com/MeanderingProgrammer/markdown.nvim?tab=readme-ov-file#colors

LMK if I missed anything, really curious how you go about integrating this. Thanks for the interest and the proposal!

**Comment by scottmckendry** [comment]
This is excellent! Pretty much exactly what I had in mind 🙂 

The only (minor) changes I would suggest would be:

1. Add H4-H6 bg groups, linking all three to the H3Bg group. This will allow me to consistently set backgrounds that match headings.
![image](https://github.com/user-attachments/assets/39a3ff43-e605-4b46-aec6-db74f74d5aae)
2. In the image above, all the signs are the same color. I think it would be a nice addition to have the sign match the fg color of each heading. 
3. Create a group for the border at the bottom of code blocks. I don't see a straightforward way of setting this currently.
![image](https://github.com/user-attachments/assets/99e5d20f-1828-4e1a-bb3e-e2bed6af021a)

**Comment by scottmckendry** [comment]
Ignore #2 in my previous comment! I've got it working now :)

![image](https://github.com/user-attachments/assets/1fbbc423-deac-40a9-ba58-0a662681f62d)

**Comment by scottmckendry** [comment]
It looks like 3 was due to the same error I was running into with the signs. This looks good now:
![image](https://github.com/user-attachments/assets/745136ab-30ea-4d4b-8e2f-ac181ba72d05)

That just leaves heading 4-6 background groups.

**Comment by MeanderingProgrammer** [comment]
Ah, understandable, updated here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/6aa19e9bf36938049e36cd97aafedfe938de8d79.

Am curious what updates you needed to make to resolve issues 2 & 3? Since if you had a `fg` defined for headings 1 through 6 I would expect the signs to be correctly colored. Similar but both a `fg` and a `bg` for the code block highlight.

**Comment by scottmckendry** [comment]
Legend! Thanks so much @MeanderingProgrammer!

Here's the final look:
![image](https://github.com/user-attachments/assets/4dd6d670-59a9-4d43-9274-8cc46b2bfa36)

**Comment by MeanderingProgrammer** [comment]
Looks great!

**Comment by jeremija** [comment]
@scottmckendry how did you solve the issue with horizontal line color? I just opened an issue #77, but now I'm wondering if there's something wrong with my config perhaps?
