### ISSUE TITLE
bug: plugin not working when lazy-loaded with cmd option

### ISSUE THREAD

**Issue by yuhsienchiang** [MeanderingProgrammer/markdown.nvim#72]
### Neovim version (nvim -v)

0.10.0

### Operating system

MacOS

### Terminal emulator / GUI

Kitty

### Describe the bug

markdown files will not be rendered if the plugin is lazy-loaded manually or with cmd option.

### Expected behavior

Markdown file being rendered after executing the command `RenderMarkdownToggle`.

### Healthcheck output (:checkhealth render-markdown)

render-markdown: require("render-markdown.health").check()

markdown.nvim [neovim version] ~
- OK Version >= 0.10

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown_inline: parser installed
- OK latex: parser installed
- OK highlights enabled

markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

### Additional information

I'm using lazy.nvim as my plugin manager and lazy-load as many plugins as possible. Therefore, I set the plugin like so:
```
return {
    "MeanderingProgrammer/markdown.nvim",
    name = "render-markdown",
    cmd = { "RenderMarkdownToggle" },
    dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },
    config = function()
        require("render-markdown").setup({})
    end,
}
```
The plugin will be loaded whenever I trigger the command. However, the plugin will not render the markdown files with this setup. Also, if I load the plugin with the command `:Lazy load render-markdown`, the plugin does not seem to be working either.

If I lazy-load the plugin based on the filetype, or load it straight away when opening neovim, the plugin works totally fine.

- lazy-load by filetype
```
return {
    "MeanderingProgrammer/markdown.nvim",
    name = "render-markdown",
    ft = { "markdown" },
    dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },
    config = function()
        require("render-markdown").setup({})
    end,
}
```

- load plugin straight away
```
return {
    "MeanderingProgrammer/markdown.nvim",
    name = "render-markdown",
    dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },
    config = function()
        require("render-markdown").setup({})
    end,
}
```

**Comment by MeanderingProgrammer** [comment]
There are 2 reasons this did not work.

1. We need to create an auto command that listens to FileType events to attach to buffers. With lazy loading by command the plugin does not create the necessary auto command in time and misses the event.
2. Toggling swaps the state from enable to disabled. Running this from the initial load would disable the plugin. So you initially lazy load, which sets the plugin state to enable, then the toggle command runs which sets the state to disabled.

Both of these are addressed in this change: https://github.com/MeanderingProgrammer/markdown.nvim/commit/3c36a257e2a5684b274c1a44fddd64183c7a7507.

I needed to add more user commands so the name of the command is now just `RenderMarkdown` which without a subcommand runs `enable`, which is what you want. The following config should work after updating the plugin:

```lua
return {
    "MeanderingProgrammer/markdown.nvim",
    name = "render-markdown",
    cmd = { "RenderMarkdown" },
    dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },
    config = function()
        require("render-markdown").setup({})
    end,
}
```

**Comment by yuhsienchiang** [comment]
Thank you for solving the issue! Also, I've set `enabled = false` so that I can use `RenderMarkdown toggle` to trigger the loading and render the markdown file without any issue.
