### ISSUE TITLE
feature: Flexible width code blocks + right-aligned language hint

### ISSUE THREAD

**Issue by serhez** [MeanderingProgrammer/markdown.nvim#73]
### Is your feature request related to a problem? Please describe.

Not a problem, just a suggestion :)

### Describe the solution you'd like

I am using this plugin over `markview.nvim` because of many key reasons, including the lower amount of errors (e.g., with rendering nested bullet lists) and the ease of setting it up for non-markdown filetypes. However, I still really like the way code blocks are rendered in `markview.nvim`. Could some of those features be implemented here? Particularly:

- Adaptable width for code blocks, depending on the width of the longest line in the block (with perhaps some minimum width). On this front, I have encountered some visual bugs in `markview.nvim` when wrapping lines that are too long, it seems to break the non-full-width code block render.
- Fight-aligned language hint.
- Right padding (currently there is only left padding); it would go well with the adaptable width feature.

### Describe alternatives you've considered

No alternatives, the plugin is still great as-is ATM.

**Comment by MeanderingProgrammer** [comment]
Right padding and adaptable width code blocks have been implemented in this PR: https://github.com/MeanderingProgrammer/markdown.nvim/pull/88!

Use `code = { width = 'block' }` & `code = { right_pad = x }`.

I'll come back to implementing the right aligned language at some point. If I don't like any implementation I come up with will provide an update.

**Comment by MeanderingProgrammer** [comment]
Oh that is strange, I am definitely not seeing the same behavior with the same config.

Can you send me the markdown file text from the screenshot, just so I can rule that out. 

Otherwise I'll need some kind of minimal reproducible which you would get by gradually disabling plugins and options. If the problem persists for instance, with only a plugin manager, nvim-treesitter, and my plugin that makes things a lot easier to reason about.

**Comment by garcia5** [comment]
Good idea that it's another plugin interfering, it was my color scheme having "transparent background" set!

https://github.com/catppuccin/nvim?tab=readme-ov-file#configuration

With this setting disabled the code block renders as expected which is fine with me. Thanks!

**Comment by MeanderingProgrammer** [comment]
Interesting if you can find a way for me to create a transparent background with virtual text feel free to create a feature request for it.

Currently we hard code the highlight for the fixed width padding to `Normal` which is the background color of most color schemes: https://github.com/MeanderingProgrammer/markdown.nvim/blob/main/lua/render-markdown/handler/markdown.lua#L260.

It makes sense that a transparent background doesn't quite work with this. But if there is a transparent highlight group that exists I can make that highlight configurable.

**Comment by MeanderingProgrammer** [comment]
Support for right aligned language hint added here: https://github.com/MeanderingProgrammer/markdown.nvim/commit/4d8b6032b659a45582089de8bcd839f8ccc4161d

Enable it with:

```lua
require('render-markdown').setup({
    code = { position = 'right' },
})
```

**Comment by benj9000** [comment]
With above's snippet (https://github.com/MeanderingProgrammer/render-markdown.nvim/issues/73#issuecomment-2262179297), I expected the language hint to be rendered aligned to the right of the window, but it depends on the length of the longest line in the code. Is that the intended behaviour?

![image](https://github.com/user-attachments/assets/72c9aefc-6168-462d-a226-0852475aaa44)

I just started playing around with this plugin, such that this comment can be considered more of an FYI than a request.

**Comment by MeanderingProgrammer** [comment]
@benj9000, it is the intended behavior, since on particularly wide windows having it all the way to the right isn't a great experience, at least that would be my opinion.

I could add something where it would be all the way to the right up to some max width, or just all the way to the right. So if either of those seem interesting to you feel free to create a feature request :)
