### ISSUE TITLE
feature: support `qmd` file from `quarto`

### ISSUE THREAD

**Issue by hopezh** [MeanderingProgrammer/markdown.nvim#76]
### Is your feature request related to a problem? Please describe.

Not related to a problem. 

### Describe the solution you'd like

Providing the same support to `qmd` file, which is basically a `markdown` file with additional syntax for the [`quarto`](https://quarto.org/) program, a "scientific and technical publishing system", especially `lsp` support for code blocks. 

### Describe alternatives you've considered

[`otter.nvim`](https://github.com/jmbuhr/otter.nvim) provides support for `qmd` files, including `lsp` for code blocks inside a `qmd` file.

**Comment by MeanderingProgrammer** [comment]
Is the file parseable as markdown?

If you add `quatro` to the file types does that work?

```lua
require('render-markdown').setup({
    file_types = { 'markdown', 'quatro' },
})
```

**Comment by hopezh** [comment]
Yes, your suggestion works like a charm. 

Now, I have `markdown.nvim` support for `quarto` `qmd` file, with `lsp` for python enabled via `[quarto-nvim](https://github.com/quarto-dev/quarto-nvim)` and `[otter.nvim](https://github.com/jmbuhr/otter.nvim)`.

It's perfect. 

![image](https://github.com/user-attachments/assets/b733c6a5-8841-4543-90a1-ed84499fd265)
