### ISSUE TITLE
bug: Concealing keeps linebreaks which might no longer be necessary

### ISSUE THREAD

**Issue by jeremija** [MeanderingProgrammer/markdown.nvim#82]
### Neovim version (nvim -v)

v0.10.0

### Operating system

Arch Linux

### Terminal emulator / GUI

Alacritty

### Describe the bug

When concealing hyperlinks, the text is split into multiple lines as if the links were still visible.

### Expected behavior

I'd expect the contents to be displayed in a single line when there is room.

### Healthcheck output (:checkhealth render-markdown)

```
==============================================================================
render-markdown: require("render-markdown.health").check()

markdown.nvim [neovim version] ~
- OK Version >= 0.10

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown_inline: parser installed
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }
- OK highlights enabled

markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }
```

### Additional information

[recording.webm](https://github.com/user-attachments/assets/9105f76f-a941-4782-b6c4-993fe4a0370e)

**Comment by MeanderingProgrammer** [comment]
Unfortunately this is a known issue that does not appear that it is going to be fixed anytime soon :(

https://github.com/neovim/neovim/issues/14409
