### ISSUE TITLE
bug: Hover doc bad arguments error

### ISSUE THREAD

**Issue by liketoeatcheese** [MeanderingProgrammer/markdown.nvim#85]
### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713484068

### Operating system

Arch Linux

### Terminal emulator / GUI

Windows Terminal Wsl2

### Describe the bug

Hey mate, first of all, love this plugin. 

This showed up whenever I opened hover doc for lsp 
![image](https://github.com/user-attachments/assets/1d6dfd6e-0d58-4999-b299-e1bf35cdb26b)

Error executing vim.schedule lua callback: ...are/nvim/lazy/render-markdown/lua/render-markdown/ui.lua:82: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
        [C]: in function 'ipairs'
        ...are/nvim/lazy/render-markdown/lua/render-markdown/ui.lua:82: in function 'refresh'
        ...are/nvim/lazy/render-markdown/lua/render-markdown/ui.lua:32: in function <...are/nvim/lazy/render-markdown/lua/render-markdown/ui.lua:30>

### Expected behavior

Lsp hover doc popped up without any errors

### Healthcheck output (:checkhealth render-markdown)

==============================================================================
render-markdown: require("render-markdown.health").check()

markdown.nvim [neovim version] ~
- OK Version >= 0.10

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown_inline: parser installed
- WARNING latex: parser not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }
- OK highlights enabled

markdown.nvim [executables] ~
- WARNING latex2text: not installed
  - ADVICE:
    - Disable LaTeX support to avoid this warning by setting { latex = { enabled = false } }

**Comment by MeanderingProgrammer** [comment]
I believe you are using a version before this commit: https://github.com/MeanderingProgrammer/markdown.nvim/commit/b7cf9e9d193b04acb73a1b6ad082d5da53115f3e, with a fix.

Can you update the plugin and see if it still happens?

**Comment by liketoeatcheese** [comment]
Yes the lastest update fixed it :) Thank you! Closing this
