### ISSUE TITLE
bug: pipeline tables not rendered correctly

### ISSUE THREAD

**Issue by raffaem** [MeanderingProgrammer/markdown.nvim#91]
### Neovim version (nvim -v)

0.10

### Operating system

Arch Linux

### Terminal emulator / GUI

Kitty

### Describe the bug

[pandoc's pipeline tables](https://pandoc.org/MANUAL.html#extension-pipe_tables) are rendered with the colons after the header.

Moreover, if the table is the first thing in the document, its horizontal line above the header is not rendered at all.

Example:
```
| **Holiday n. 1** |            |
|:-----------------|:-----------|
| Start            | 2024-06-03 |
| End              | 2024-06-18 |
| Accounting       | 2024-06-25 |

| **Holiday n. 2** |            |
|:-----------------|:-----------|
| Start            | 2024-06-03 |
| End              | 2024-06-18 |
| Accounting       | 2024-06-25 |
```

Screenshot:
![image](https://github.com/user-attachments/assets/a90dfde9-954a-45c3-908b-6c5350c6064c)

### Expected behavior

Tables should be rendered without the colons that describe the alignment (and correct alignment of the columns) and the first table should be rendered with the first line above its header

### Healthcheck output (:checkhealth render-markdown)

render-markdown: require("render-markdown.health").check()

markdown.nvim [neovim version] ~
- OK Version >= 0.10

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown_inline: parser installed
- OK latex: parser installed
- OK highlights enabled

markdown.nvim [executables] ~
- OK latex2text: installed

**Comment by raffaem** [comment]
> Automatic column alignment will not be done by this plugin.

I mean only visually of course.

The colons signal the column alignment.

**Comment by MeanderingProgrammer** [comment]
I am aware of what the colon signals. 

If you want this plugin to take a left aligned column and align it to the right because the colon for the column is on the right side, even "only visually" that will not happen.

**Comment by MeanderingProgrammer** [comment]
Alignment indicators added in this commit: https://github.com/MeanderingProgrammer/markdown.nvim/commit/a27303384570b85ee4538fa5f30eb418fef01ec7, which replace the colons.

Have a todo to maybe handle column alignment but I'll track separately.

Please update and LMK what ya think.

**Comment by raffaem** [comment]
Interesting, here is the new rendering of the example for reference:

![image](https://github.com/user-attachments/assets/83da96ba-8fcd-4474-90e6-db25979990f0)
