### ISSUE TITLE
bug: LaTeX code rendered on top of the code

### ISSUE THREAD

**Issue by raffaem** [MeanderingProgrammer/markdown.nvim#97]
### Neovim version (nvim -v)

0.10

### Operating system

Arch Linux

### Terminal emulator / GUI

kitty

### Describe the bug

Latex code is rendered above the paragraph that contains it instead of in its place

```
You need to go to the hospital if your body temperature is $ \ge 40$.
```

![image](https://github.com/user-attachments/assets/be390971-c9c7-4889-b661-7a44eb47f26a)

### Expected behavior

The rendered equation should substitute the equation code, not be rendered on top of it

### Healthcheck output

==============================================================================
render-markdown: require("render-markdown.health").check()

markdown.nvim [neovim version] ~
- OK Version >= 0.10

markdown.nvim [configuration] ~
- OK valid

markdown.nvim [nvim-treesitter] ~
- OK installed
- OK markdown: parser installed
- OK markdown: highlight enabled
- OK markdown_inline: parser installed
- OK markdown_inline: highlight enabled
- OK latex: parser installed

markdown.nvim [executables] ~
- OK latex2text: installed

markdown.nvim [conflicts] ~
- OK headlines: not installed
- OK obsidian: not installed

### Plugin configuration

Default configuration

```
return {
  'MeanderingProgrammer/markdown.nvim',
  main = "render-markdown",
  opts = {},
  name = 'render-markdown',                                                      -- Only needed if you have another plugin named markdown.nvim
  -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.nvim' }, -- if you use the mini.nvim suite
  -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.icons' }, -- if you use standalone mini plugins
  dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' }, -- if you prefer nvim-web-devicons
}
```

### Confirmations

- [X] I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not

**Comment by MeanderingProgrammer** [comment]
Yep, too hard to fix, no plans on it. Open to PRs though. 

https://github.com/MeanderingProgrammer/markdown.nvim/blob/main/doc%2Flimitations.md
